//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHUNGTUCHITIET
    {
        public System.Guid KhoaCT { get; set; }
        public Nullable<System.Guid> Khoa { get; set; }
        public string MaDVI { get; set; }
        public string SCT { get; set; }
        public string SCT2 { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tb_DONVI tb_DONVI { get; set; }
    }
}
