//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HANGHOA
    {
        public string MaHH { get; set; }
        public string TenHH { get; set; }
        public int DVT { get; set; }
        public string MaNCC { get; set; }
        public string XuatXu { get; set; }
        public Nullable<decimal> TonKho { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string GhiChu { get; set; }
        public string TENTAT { get; set; }
    
        public virtual tb_DONVITINH tb_DONVITINH { get; set; }
        public virtual tb_NHACUNGCAP tb_NHACUNGCAP { get; set; }
    }
}
